/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 25-jun-2018 15:04:28 				*/
/*  DBMS       : MSAccess 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [BDN_Colecciones_MAGRAMA]
(
	[IdColecciones_Magrama] Long NOT NULL,
	[Colecciones_Magrama] Text(255) NULL,
	[ID_componente] Long NULL,
	[Anio] Long NULL,
	[Depende_ambito] Short NULL,
	CONSTRAINT [Id] PRIMARY KEY ([IdColecciones_Magrama])
)
;

CREATE TABLE [BDN_Refrendado]
(
	[IdRefrendado] Long NOT NULL,
	[Refrendado] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdRefrendado])
)
;

CREATE TABLE [Colecciones_Magrama]
(
	[TaxonId] Long NOT NULL,
	[IdColeccionesMagrama] Long NOT NULL,
	[idcountry] Long NOT NULL,
	[Código] Text(255) NULL,
	[Taxon_Nombre_colec] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([TaxonId],[IdColeccionesMagrama],[idcountry]),
	CONSTRAINT [BDN_Colecciones_MAGRAMAColecciones_Magrama] FOREIGN KEY ([IdColeccionesMagrama]) REFERENCES [BDN_Colecciones_MAGRAMA] ([IdColecciones_Magrama]),
	CONSTRAINT [T_countryColecciones_Magrama] FOREIGN KEY ([idcountry]) REFERENCES [T_country] ([Idcountry]),
	CONSTRAINT [TaxonColecciones_Magrama] FOREIGN KEY ([TaxonId]) REFERENCES [Taxon] ([TaxonID])
)
;

CREATE TABLE [Distribution]
(
	[idDistribution] Long NOT NULL,
	[IdDistributionType] Long NOT NULL,
	[IDDistributionScope] Long NULL,
	[IdDistributionScopeType] Long NULL,
	[iddistributionGeoentity] Double NULL,
	[TemporalCoverage] Text(50) NULL,
	[GeographicEntity] Text(255) NOT NULL,
	[TaxonRecordId] Long NOT NULL,
	[DistributionRemarks] Memo NULL,
	[DistributionURL] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idDistribution],[IdDistributionType],[GeographicEntity],[TaxonRecordId]),
	CONSTRAINT [PlinianCore-ExtensionDistribution] FOREIGN KEY ([TaxonRecordId]) REFERENCES [PlinianCore-Extension] ([TaxonRecordId]),
	CONSTRAINT [T_Distribution_GeoEntityDistribution] FOREIGN KEY ([iddistributionGeoentity]) REFERENCES [T_Distribution_GeoEntity] ([iddistributionGeoentity]),
	CONSTRAINT [T_DistributionScopeDistribution] FOREIGN KEY ([IDDistributionScope]) REFERENCES  (),
	CONSTRAINT [T_DistributionScopeTypeDistribution] FOREIGN KEY ([IdDistributionScopeType]) REFERENCES  (),
	CONSTRAINT [T_DistributionType_invDistribution] FOREIGN KEY ([IdDistributionType]) REFERENCES  ()
)
;

CREATE TABLE [dwc:Location]
(
	[locationID] Long NULL,
	[higherGeographyID] Text(255) NULL,
	[higherGeography] Text(255) NULL,
	[continent] Text(255) NULL,
	[waterBody] Text(255) NULL,
	[islandGroup] Text(255) NULL,
	[island] Text(255) NULL,
	[country] Text(255) NULL,
	[countryCode] Text(255) NULL,
	[stateProvince] Text(255) NULL,
	[county] Text(255) NULL,
	[municipality] Text(255) NULL,
	[locality] Text(255) NULL,
	[verbatimLocality] Text(255) NULL,
	[verbatimElevation] Text(255) NULL,
	[minimumElevationInMeters] Double NULL,
	[maximumElevationInMeters] Double NULL,
	[verbatimDepth] Text(255) NULL,
	[minimumDepthInMeters] Double NULL,
	[maximumDepthInMeters] Double NULL,
	[minimumDistanceAboveSurfaceInMeters] Double NULL,
	[maximumDistanceAboveSurfaceInMeters] Double NULL,
	[locationAccordingTo] Text(255) NULL,
	[locationRemarks] Text(255) NULL,
	[verbatimCoordinates] Text(255) NULL,
	[verbatimLatitude] Text(255) NULL,
	[verbatimLongitude] Text(255) NULL,
	[verbatimCoordinateSystem] Text(255) NULL,
	[verbatimSRS] Text(255) NULL,
	[decimalLatitude] Double NULL,
	[decimalLongitude] Double NULL,
	[geodeticDatum] Text(255) NULL,
	[coordinateUncertaintyInMeters] Double NULL,
	[coordinatePrecision] Text(255) NULL,
	[pointRadiusSpatialFit] Text(255) NULL,
	[footprintWKT] Text(255) NULL,
	[footprintSRS] Memo NULL,
	[footprintSpatialFit] Text(255) NULL,
	[georeferencedBy] Text(255) NULL,
	[georeferencedDate] Text(255) NULL,
	[georeferenceProtocol] Text(255) NULL,
	[georeferenceSources] Text(255) NULL,
	[georeferenceVerificationStatus] Text(255) NULL,
	[georeferenceRemarks] Text(255) NULL,
	[TaxonID] Long NULL,
	[IdColeccionesMagrama] Long NULL,
	[CUTM10x10] Text(255) NULL,
	[EstadoCUTM] Text(255) NULL,
	[FechaCUTM] DateTime NULL,
	[CUTM1x1] Text(255) NULL,
	[CLAEA10x10] Text(255) NULL,
	CONSTRAINT [T_CoordinateSystemdwc:Location] FOREIGN KEY ([verbatimSRS]) REFERENCES  (),
	CONSTRAINT [T_MALLA_UTM10X10dwc:Location] FOREIGN KEY ([CUTM10x10]) REFERENCES  (),
	CONSTRAINT [Taxondwc:Location] FOREIGN KEY ([TaxonID]) REFERENCES  ()
)
;

CREATE TABLE [dwc:MeasurementOrFact]
(
	[measurementID] Long NOT NULL,
	[IdmeasurementType] Long NULL,
	[measurementValue] Text(255) NULL,
	[measurementAccuracy] Text(255) NULL,
	[idmeasurementUnit] Long NULL,
	[measurementDeterminedDate] Text(50) NULL,
	[measurementDeterminedBy] Text(50) NULL,
	[idmeasurementMethod] Long NULL,
	[measurementRemarks] Text(255) NULL,
	[TaxonID] Long NULL,
	[idmeasurementContamination] Long NULL,
	[AppliesTo] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([measurementID]),
	CONSTRAINT [FK_dwc:MeasurementOrFact_T_MeasurementAccuracy] FOREIGN KEY ([measurementAccuracy]) REFERENCES  (),
	CONSTRAINT [FK_dwc:MeasurementOrFact_T_Measurementmethod] FOREIGN KEY ([idmeasurementMethod]) REFERENCES  (),
	CONSTRAINT [FK_dwc:MeasurementOrFact_T_poblacion_applies] FOREIGN KEY ([AppliesTo]) REFERENCES  (),
	CONSTRAINT [T_MeasurementTypedwc:MeasurementOrFact] FOREIGN KEY ([IdmeasurementType]) REFERENCES  (),
	CONSTRAINT [T_measurementUnitdwc:MeasurementOrFact] FOREIGN KEY ([idmeasurementUnit]) REFERENCES  (),
	CONSTRAINT [Taxondwc:MeasurementOrFact] FOREIGN KEY ([TaxonID]) REFERENCES  ()
)
;

CREATE TABLE [dwc:ResourceRelationship]
(
	[resourceRelationshipId] Long NOT NULL,
	[relatedResourceID] Long NULL,
	[relationshipOfResource] Text(50) NULL,
	[relationshipAccordingTo] Text(50) NULL,
	[relationshipEstablishedDate] Text(50) NULL,
	[relationshipRemarks] Memo NULL,
	[scientificName] Text(50) NULL,
	[TaxonID] Long NULL,
	[IDrelatedResourceType] Long NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([resourceRelationshipId]),
	CONSTRAINT [T_RelatedResourceTypedwc:ResourceRelationship] FOREIGN KEY ([IDrelatedResourceType]) REFERENCES  (),
	CONSTRAINT [Taxondwc:ResourceRelationship] FOREIGN KEY ([TaxonID]) REFERENCES  ()
)
;

CREATE TABLE [Endemic]
(
	[idEndemic] Long NOT NULL,
	[EndemicTo] Text(255) NULL,
	[IDEndemicIn] Long NULL,
	[TaxonRecordID] Long NULL,
	[additionalInformation] Memo NULL,
	[Id] Long NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idEndemic])
)
;

CREATE TABLE [EOL:Media]
(
	[idMedia] Long NOT NULL,
	[IdType] Long NULL,
	[subtype] Text(50) NULL,
	[format] Long NULL,
	[CVterm] Text(50) NULL,
	[title] Text(50) NULL,
	[description] Text(50) NULL,
	[accessURI] Text(50) NULL,
	[thumbnailURL] Text(50) NULL,
	[furtherInformationURL] Text(50) NULL,
	[derivedFrom] Text(50) NULL,
	[CreateDate] DateTime NULL,
	[modified] DateTime NULL,
	[language] Text(50) NULL,
	[Rating] Text(50) NULL,
	[IdAudience] Long NULL,
	[Usage Terms] Text(50) NULL,
	[rights] Text(50) NULL,
	[Owner] Text(50) NULL,
	[bibliographicCitation] Text(50) NULL,
	[publisher] Text(50) NULL,
	[contributor] Text(50) NULL,
	[creator] Text(50) NULL,
	[agentID] Text(50) NULL,
	[LocationCreated] Text(50) NULL,
	[spatial] Text(50) NULL,
	[lat] Double NULL,
	[long] Double NULL,
	[alt] Double NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idMedia]),
	CONSTRAINT [T_TypeEOL:Media] FOREIGN KEY ([IdType]) REFERENCES  ()
)
;

CREATE TABLE [EOL:Media-EOL:Reference]
(
	[idMedia] Long NOT NULL,
	[idReference] Long NOT NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idMedia],[idReference]),
	CONSTRAINT [EOL:MediaEOL:Media-EOL:Reference] FOREIGN KEY ([idMedia]) REFERENCES  (),
	CONSTRAINT [EOL:ReferenceEOL:Media-EOL:Reference] FOREIGN KEY ([idReference]) REFERENCES  ()
)
;

CREATE TABLE [EOL:Reference]
(
	[idReference] Long NOT NULL,
	[IdPublicationType] Long NULL,
	[full_reference] Memo NULL,
	[primaryTitle] Text(255) NULL,
	[title] Text(255) NULL,
	[pages] Text(50) NULL,
	[pageStart] Text(50) NULL,
	[pageEnd] Text(50) NULL,
	[volume] Text(50) NULL,
	[edition] Text(255) NULL,
	[publisher] Text(255) NULL,
	[authorList] Text(255) NULL,
	[editorList] Text(50) NULL,
	[created] Text(50) NULL,
	[language] Text(50) NULL,
	[uri] Text(255) NULL,
	[doi] Text(50) NULL,
	[localityName] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idReference]),
	CONSTRAINT [T_PublicationTypeEOL:Reference] FOREIGN KEY ([IdPublicationType]) REFERENCES  ()
)
;

CREATE TABLE [GISIN:Invasiveness]
(
	[idInvasiveness] Long NOT NULL,
	[TaxonID] Long NULL,
	[IdAbundance] Long NULL,
	[IdDistribution] Long NULL,
	[IdHarmful] Long NULL,
	[IdOrigin] Long NULL,
	[IdPersistence] Long NULL,
	[IdPresence] Long NULL,
	[PublicationDate] DateTime NULL,
	[IdrateOfspread] Long NULL,
	[IdRegulatoryListing] Long NULL,
	[IdTrend] Long NULL,
	[IdRoute] Long NULL,
	[Citation] Text(50) NULL,
	[Concept] Text(50) NULL,
	[Count] Text(50) NULL,
	[IdcountryCode] Long NULL,
	[county] Text(50) NULL,
	[modified] DateTime NULL,
	[DateLastModifiedMax] DateTime NULL,
	[DateLastModifiedMin] DateTime NULL,
	[EndValidDate] DateTime NULL,
	[IdKingdom] Long NULL,
	[IdLanguage] Long NULL,
	[Limit] Long NULL,
	[LocalityName] Text(50) NULL,
	[IdLocalityType] Long NULL,
	[IdLocationStandard] Long NULL,
	[LocationValue] Text(50) NULL,
	[Memo] Memo NULL,
	[scientificName] Text(255) NULL,
	[Start] Long NULL,
	[StartValidDate] DateTime NULL,
	[stateProvince] Text(50) NULL,
	[ValidDatemax] DateTime NULL,
	[validdateMin] DateTime NULL,
	[IdImpactTarget] Long NULL,
	[WhatImpact] Text(255) NULL,
	[Vector] Memo NULL,
	[Fuente_vector] Text(255) NULL,
	[DistributionUnstructured] Memo NULL,
	[Fuente_distributionUnstructured] Text(255) NULL,
	[impactMechanism] Text(255) NULL,
	[EconomicCost] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idInvasiveness]),
	CONSTRAINT [T_Country_codesGISIN:Invasiveness] FOREIGN KEY ([IdcountryCode]) REFERENCES  (),
	CONSTRAINT [T_GISIN_distributionGISIN:Invasiveness] FOREIGN KEY ([IdDistribution]) REFERENCES  (),
	CONSTRAINT [T_GISIN_LanguageGISIN:Invasiveness] FOREIGN KEY ([IdLanguage]) REFERENCES  (),
	CONSTRAINT [T_GISIN_originGISIN:Invasiveness] FOREIGN KEY ([IdOrigin]) REFERENCES  (),
	CONSTRAINT [T_GISIN_trendGISIN:Invasiveness] FOREIGN KEY ([IdTrend]) REFERENCES  (),
	CONSTRAINT [TaxonGISIN:Invasiveness] FOREIGN KEY ([TaxonID]) REFERENCES  ()
)
;

CREATE TABLE [GISIN:Invasiveness-n]
(
	[idInvasivenessn] Long NOT NULL,
	[TaxonID] Long NULL,
	[IdAbundance] Long NULL,
	[IdDistribution] Long NULL,
	[IdHarmful] Long NULL,
	[IdOrigin] Long NULL,
	[IdPersistence] Long NULL,
	[IdPresence] Long NULL,
	[PublicationDate] DateTime NULL,
	[IdrateOfspread] Long NULL,
	[IdRegulatoryListing] Long NULL,
	[IdTrend] Long NULL,
	[IdRoute] Long NULL,
	[Citation] Text(50) NULL,
	[Concept] Text(50) NULL,
	[Count] Text(50) NULL,
	[IdcountryCode] Long NULL,
	[county] Text(50) NULL,
	[modified] DateTime NULL,
	[DateLastModifiedMax] DateTime NULL,
	[DateLastModifiedMin] DateTime NULL,
	[EndValidDate] DateTime NULL,
	[IdKingdom] Long NULL,
	[IdLanguage] Long NULL,
	[Limit] Long NULL,
	[LocalityName] Text(50) NULL,
	[IdLocalityType] Long NULL,
	[IdLocationStandard] Long NULL,
	[LocationValue] Text(50) NULL,
	[Memo] Memo NULL,
	[scientificName] Text(255) NULL,
	[Start] Long NULL,
	[StartValidDate] DateTime NULL,
	[stateProvince] Text(50) NULL,
	[ValidDatemax] DateTime NULL,
	[validdateMin] DateTime NULL,
	[IdImpactTarget] Long NULL,
	[WhatImpact] Text(255) NULL,
	[Fuente_impact] Text(255) NULL,
	[Vector] Memo NULL,
	[Fuente_vector] Text(255) NULL,
	[DistributionUnstructured] Memo NULL,
	[Fuente_distributionUnstructured] Text(255) NULL,
	[impactMechanism] Text(255) NULL,
	[EconomicCost] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idInvasivenessn]),
	CONSTRAINT [T_GISIN_impactTargetGISIN:Invasiveness-n] FOREIGN KEY ([IdImpactTarget]) REFERENCES  (),
	CONSTRAINT [TaxonGISIN:Invasiveness-n] FOREIGN KEY ([TaxonID]) REFERENCES  ()
)
;

CREATE TABLE [Invasiveness_RedAlerta]
(
	[idInvasivenessred] Long NOT NULL,
	[TaxonID] Long NULL,
	[idambitored] Long NULL,
	[RedAlerta] Text(255) NULL,
	[Fuente_redalerta] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idInvasivenessred]),
	CONSTRAINT [T_ambitoRedInvasiveness_RedAlerta] FOREIGN KEY ([idambitored]) REFERENCES [T_ambitoRed] ([Idambitored]),
	CONSTRAINT [TaxonInvasiveness_RedAlerta] FOREIGN KEY ([TaxonID]) REFERENCES [Taxon] ([TaxonID])
)
;

CREATE TABLE [Legislation]
(
	[idLegislation] Long NOT NULL,
	[LegislationName] Text(255) NULL,
	[IdProtectionLegalStatus] Long NOT NULL,
	[LegislationRead] Text(255) NULL,
	[IdStatus] Long NULL,
	[IdType_sup] Long NULL,
	[IdType_int] Long NULL,
	[IdType_inf] Long NULL,
	[IdNorm] Long NULL,
	[IdAppliesTo] Long NOT NULL,
	[TaxonRecordId] Long NOT NULL,
	[Remarks] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idLegislation],[IdProtectionLegalStatus],[IdAppliesTo],[TaxonRecordId]),
	CONSTRAINT [PlinianCore-ExtensionLegislation] FOREIGN KEY ([TaxonRecordId]) REFERENCES [PlinianCore-Extension] ([TaxonRecordId]),
	CONSTRAINT [T_Legislation_appliesToLegislation] FOREIGN KEY ([IdAppliesTo]) REFERENCES  (),
	CONSTRAINT [T_NORMASLegislation] FOREIGN KEY ([idLegislation]) REFERENCES  (),
	CONSTRAINT [T_ProtectionlegalStatusLegislation] FOREIGN KEY ([IdProtectionLegalStatus]) REFERENCES [T_legislation_ProtectionlegalStatus] ([IdProtectionlegalstatus]),
	CONSTRAINT [T_StatusLegislation] FOREIGN KEY ([IdStatus]) REFERENCES [T_Status] ([IdStatus])
)
;

CREATE TABLE [ManagementAndConservation]
(
	[idManagementAndConservation] Long NOT NULL,
	[IdManagementAndConservationType] Long NULL,
	[IdObjectives] Long NULL,
	[ManagementPlan] Text(255) NULL,
	[Actions] Text(255) NULL,
	[HumanAndEnvironmentalRelevance] Text(50) NULL,
	[TaxonRecordId] Long NULL,
	[ManagementRemarks] Text(255) NULL,
	[ManagementDate] DateTime NULL,
	[ManagementURL] Text(255) NULL,
	[id_es_agrup] Long NULL,
	[id_nut_1] Long NULL,
	[id_nut_2] Long NULL,
	[id_nut_3] Long NULL,
	[id_reg_bio] Long NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idManagementAndConservation]),
	CONSTRAINT [PlinianCore-ExtensionManagementAndConservation] FOREIGN KEY ([TaxonRecordId]) REFERENCES [PlinianCore-Extension] ([TaxonRecordId]),
	CONSTRAINT [T_ES_agrupManagementAndConservation] FOREIGN KEY ([id_es_agrup]) REFERENCES  (),
	CONSTRAINT [T_Manag_ObjectivesManagementAndConservation] FOREIGN KEY ([IdObjectives]) REFERENCES [T_Manag_Objectives] ([IdObjectives]),
	CONSTRAINT [T_Managtype_medConsGestManagementAndConservation] FOREIGN KEY ([IdManagementAndConservationType]) REFERENCES [T_Managtype_medConsGest] ([IdManagementAndConservationType]),
	CONSTRAINT [T_NUTSManagementAndConservation] FOREIGN KEY ([id_nut_2]) REFERENCES  ()
)
;

CREATE TABLE [Names]
(
	[ScientificNameId] Long NOT NULL,
	[nomenclaturalCode] Text(50) NULL,
	[scientificName] Text(255) NULL,
	[scientificNameAuthorship] Text(50) NULL,
	[namePublishedIn] Text(50) NULL,
	[namePublishedInYear] Text(50) NULL,
	[originalNameUsage] Text(50) NULL,
	[SynonymStatus] Text(255) NULL,
	[acceptedNameUsageID] Long NULL,
	[acceptedNameUsage] Text(255) NULL,
	[IdTaxonomicStatus] Long NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([ScientificNameId]),
	CONSTRAINT [T_TaxonomicStatusNames] FOREIGN KEY ([IdTaxonomicStatus]) REFERENCES [T_TaxonomicStatus] ([IdTaxonomicStatus]),
	CONSTRAINT [TaxonNames] FOREIGN KEY ([ScientificNameId]) REFERENCES [Taxon] ([TaxonID])
)
;

CREATE TABLE [PlinianCore-Extension]
(
	[TaxonRecordId] Long NOT NULL,
	[GlobalUniqueIdentifier] Text(255) NULL,
	[Abstract] Text(255) NULL,
	[AudiencesUnstructured] Text(255) NULL,
	[SynonymsUnstructured] Memo NULL,
	[DetailUnstructured] Text(255) NULL,
	[BriefDescription] Text(255) NULL,
	[Fuente_BriefDescription] Text(255) NULL,
	[FullDescriptionUnstructured] Memo NULL,
	[Fuente_FullDescription] Text(255) NULL,
	[Keys] Text(255) NULL,
	[LifeFormUnstructured] Text(255) NULL,
	[LifeCycleUnstructured] Memo NULL,
	[Fuente_lifecycle] Text(255) NULL,
	[ReproductionUnstructured] Text(255) NULL,
	[AnnualCycleEvent] Text(255) NULL,
	[AnnualCycleStartTimeInterval] Text(255) NULL,
	[AnnualCycleEndTimeInterval] Text(255) NULL,
	[AnnualCycleUnstructured] Text(255) NULL,
	[FeedingType] Text(255) NULL,
	[FeedingThropicStrategy] Text(255) NULL,
	[FeedingThropicStrategyRemarks] Text(255) NULL,
	[FeedingUnstructured] Memo NULL,
	[Fuente_feeding] Text(255) NULL,
	[DispersalType] Text(255) NULL,
	[StructureDispersed] Text(255) NULL,
	[DispersalUnstructured] Text(255) NULL,
	[BehaviourUnstructured] Memo NULL,
	[Fuente_behaviour] Text(255) NULL,
	[InteractionSpeciesType] Text(255) NULL,
	[InteractionUnstructured] Memo NULL,
	[MolecularDataUnstructured] Text(255) NULL,
	[MigratoryUnstructured] Text(255) NULL,
	[EcologicalSignificanceUnstructured] Text(255) NULL,
	[EnvironmentalEnvelopeUnstructured] Text(255) NULL,
	[WhatImpact] Text(255) NULL,
	[Vector] Memo NULL,
	[Route] Text(255) NULL,
	[impactTarget] Memo NULL,
	[impactMechanism] Memo NULL,
	[InvasivenessUnstructured] Memo NULL,
	[Fuente_invasiveness] Text(255) NULL,
	[HabitatUnstructured] Memo NULL,
	[Fuente_Habitat] Text(255) NULL,
	[DistributionUnstructured] Memo NULL,
	[Fuente_Distribution] Text(255) NULL,
	[EndemicUnstructured] Memo NULL,
	[fuente_endemic] Text(255) NULL,
	[TerritoryUnstructured] Text(255) NULL,
	[PopulationBiologyUnstructured] Memo NULL,
	[Fuente_PopulationBiology] Text(255) NULL,
	[PopulationTrendUnstructured] Memo NULL,
	[Fuente_PopulationTrend] Text(255) NULL,
	[ThreatStatusUnstructured] Memo NULL,
	[Fuente_threatStatus] Text(255) NULL,
	[DirectThreatUnstructured] Memo NULL,
	[Fuente_directThreat] Text(255) NULL,
	[LegislationUnstructured] Text(255) NULL,
	[UsesUnstructured] Text(255) NULL,
	[ManagementAndConservationUnstructured] Memo NULL,
	[Fuente_ManagementAndConservation] Text(255) NULL,
	[ConservationMeasurementUnstructured] Memo NULL,
	[Fuente_ConservationMeasurement] Text(255) NULL,
	[HumanAndEnvironmentalRelevanceUnstructured] Memo NULL,
	[Fuente_HumanAndEnvironmentalRelevance] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([TaxonRecordId])
)
;

CREATE TABLE [PropuestaAdministrativa]
(
	[idpropuesta] Long NULL,
	[TaxonId] Long NOT NULL,
	[Propuesta] Text(255) NULL,
	[Solicitante] Memo NULL,
	[Expertos] Text(255) NULL,
	[Justificacion] Memo NULL,
	[Fuente] Memo NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([TaxonId]),
	CONSTRAINT [TaxonPropuestaAdministrativa] FOREIGN KEY ([TaxonId]) REFERENCES [Taxon] ([TaxonID])
)
;

CREATE TABLE [T_ambitoRed]
(
	[Idambitored] Long NOT NULL,
	[AmbitoRed] Text(50) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([Idambitored])
)
;

CREATE TABLE [T_AMBITOS]
(
	[COD_AMBITO] Text(2) NOT NULL,
	[AMBITO] Text(50) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([COD_AMBITO])
)
;

CREATE TABLE [T_COMPONENTES]
(
	[ID_COMPONENTE] Long NOT NULL,
	[COMPONENTE] Text(255) NULL,
	[ID_TEMA] Long NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([ID_COMPONENTE]),
	CONSTRAINT [{72CCCA09-4C14-47D0-ACA0-E4DA47F19764}] FOREIGN KEY ([ID_TEMA]) REFERENCES [T_TEMAS] ([ID_TEMA])
)
;

CREATE TABLE [T_CoordinateSystem]
(
	[Idcoord] Short NULL,
	[verbatimSRS] Text(255) NOT NULL,
	[verbatimCoordinateSystem] Text(255) NULL,
	[footprintSRS] Memo NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([verbatimSRS])
)
;

CREATE TABLE [T_country]
(
	[Idcountry] Long NOT NULL,
	[country] Text(10) NULL,
	[country_txt] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([Idcountry])
)
;

CREATE TABLE [T_Country_codes]
(
	[Country name] Text(255) NULL,
	[ISO3] Text(3) NULL,
	[ISO2] Text(2) NULL,
	[parent_iso3] Text(3) NULL
)
;

CREATE TABLE [T_Distribution_GeoEntity]
(
	[Id] Counter NOT NULL,
	[IddistributionSCOPEtype] Double NULL,
	[iddistributionScope] Double NULL,
	[iddistributionGeoentity] Double NOT NULL,
	[nut2] Long NULL,
	[codigo] Text(255) NULL,
	[geoent] Text(255) NULL,
	[geoEntity] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([iddistributionGeoentity])
)
;

CREATE TABLE [T_DistributionScope]
(
	[IDDISTRIBUTIONSCOPETYPE] Long NULL,
	[IdDistributionScope] Long NULL,
	[DistributionScope] Text(255) NULL
)
;

CREATE TABLE [T_DistributionScopeType]
(
	[IdDistributionScopeType] Long NULL,
	[DistributionScopeType] Text(255) NULL
)
;

CREATE TABLE [T_DistributionType]
(
	[IdDistributionType] Long NULL,
	[DistributionType] Text(50) NULL,
	CONSTRAINT [DistributionT_DistributionType] FOREIGN KEY ([IdDistributionType]) REFERENCES  ()
)
;

CREATE TABLE [T_DistributionType_inv]
(
	[IdDistributionType] Long NULL,
	[DistributionType] Text(50) NULL
)
;

CREATE TABLE [T_EndemicIN]
(
	[IDEndemicIn] Long NULL,
	[EndemicIn] Text(255) NULL,
	[idEndemic] Long NULL,
	CONSTRAINT [EndemicT_EndemicIN] FOREIGN KEY ([idEndemic]) REFERENCES [Endemic] ([idEndemic])
)
;

CREATE TABLE [T_ES_unidadesGeo]
(
	[Id_es] Long NULL,
	[Es_agrup] Text(255) NULL
)
;

CREATE TABLE [T_Estado_cuadricula]
(
	[IDESTADO] Long NULL,
	[ESTADOCUTM] Text(50) NULL,
	[OBSERVACIONES] Text(255) NULL,
	CONSTRAINT [dwc:LocationT_Estado_cuadricula] FOREIGN KEY ([ESTADOCUTM]) REFERENCES  ()
)
;

CREATE TABLE [T_GISIN_distribution]
(
	[IdDistribution] Long NOT NULL,
	[Distribucion] Text(250) NULL,
	[Descripcion] Memo NULL,
	[Fuente] Memo NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdDistribution])
)
;

CREATE TABLE [T_GISIN_impactTarget]
(
	[IdImpactTarget] Long NOT NULL,
	[ImpactTarget] Text(50) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdImpactTarget])
)
;

CREATE TABLE [T_GISIN_Language]
(
	[IdLanguage] Long NOT NULL,
	[CodLanguage] Text(3) NULL,
	[Language] Text(50) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdLanguage])
)
;

CREATE TABLE [T_GISIN_origin]
(
	[IdOrigin] Long NOT NULL,
	[Origen] Text(255) NULL,
	[Origin] Text(50) NULL,
	[Description] Memo NULL,
	[Fuente] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdOrigin])
)
;

CREATE TABLE [T_GISIN_route]
(
	[Idroute] Long NULL,
	[IntroVia] Text(255) NULL,
	[Nombre] Memo NULL,
	[Descripción] Memo NULL,
	[Fuente] Memo NULL,
	[TipoIntroduccion] Text(50) NULL,
	[CodViasEntrada] Text(50) NULL,
	CONSTRAINT [GISIN:Invasiveness-nT_GISIN_route] FOREIGN KEY ([Idroute]) REFERENCES  ()
)
;

CREATE TABLE [T_GISIN_trend]
(
	[idTrend] Long NOT NULL,
	[TendenciaPoblacional] Text(50) NULL,
	[Trend] Text(50) NULL,
	[Description] Text(50) NULL,
	[Fuente] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idTrend])
)
;

CREATE TABLE [T_grupoTaxonomico]
(
	[Idgrupotax] Long NOT NULL,
	[grupotax] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([Idgrupotax])
)
;

CREATE TABLE [T_Language]
(
	[IdLanguage] Long NOT NULL,
	[CodLanguage] Text(3) NULL,
	[Language] Text(50) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdLanguage])
)
;

CREATE TABLE [T_legislation_AMBITO_PROTECCION]
(
	[idambitoProteccion] Long NOT NULL,
	[name] Text(255) NULL,
	[descripcion] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idambitoProteccion])
)
;

CREATE TABLE [T_Legislation_appliesTo]
(
	[IdAppliesTo] Long NULL,
	[Appliesto] Text(255) NULL,
	[IdAmbitoProteccion] Long NULL,
	[idorganismo] Long NULL,
	[Nut2] Long NULL,
	CONSTRAINT [T_legislation_AMBITO_PROTECCIT_Legislation_appliesTo] FOREIGN KEY ([IdAmbitoProteccion]) REFERENCES [T_legislation_AMBITO_PROTECCION] ([idambitoProteccion])
)
;

CREATE TABLE [T_legislation_ProtectionlegalStatus]
(
	[IdProtectionlegalstatus] Long NOT NULL,
	[IdAppliesTo] Long NULL,
	[IdLegislation] Long NULL,
	[IdNorm] Long NULL,
	[ProtectionLegalStatus] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdProtectionlegalstatus])
)
;

CREATE TABLE [T_MALLA_UTM10X10]
(
	[ID] Counter NOT NULL,
	[POS] Text(255) NULL,
	[COD100K] Text(255) NULL,
	[XCENTROIDE] Double NULL,
	[YCENTROIDE] Double NULL,
	[X] Double NULL,
	[Y] Double NULL,
	[UTMCODE] Text(255) NULL,
	[CUADRICULA] Text(255) NOT NULL,
	[MARINO] Double NULL,
	[COD100X100] Text(255) NULL,
	[PERIM_km] Double NULL,
	[Area_km2] Double NULL,
	[COD_INB] Double NULL,
	[AMBITO] Text(1) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([CUADRICULA])
)
;

CREATE TABLE [T_MALLA_UTM1x1]
(
	[OBJECTID] Counter NOT NULL,
	[Cod_Prov] Text(2) NULL,
	[Provincia] Text(50) NULL,
	[Cod_CCAA] Text(2) NULL,
	[ComAutonom] Text(50) NULL,
	[COD_Muni] Text(255) NULL,
	[NOMBRE] Text(255) NULL,
	[HUSO] Text(2) NULL,
	[ZONA] Text(1) NULL,
	[CUADRI100] Text(2) NULL,
	[CUADRI10] Text(2) NULL,
	[NUTM] Text(16) NULL,
	[UTM] Text(4) NULL,
	[UTMCODE1X1] Text(16) NULL,
	[CUTM1X1] Text(16) NULL,
	[CUTM10X10] Text(16) NULL,
	[Area_muni] Single NULL,
	[Area_Malla] Single NULL,
	[Area_parcial] Double NULL,
	[Porc_Muni_cUTM] Double NULL,
	CONSTRAINT [T_MALLA_UTM10X10T_MALLA_UTM1x1] FOREIGN KEY ([CUTM10X10]) REFERENCES [T_MALLA_UTM10X10] ([CUADRICULA])
)
;

CREATE TABLE [T_Manag_Objectives]
(
	[IdObjectives] Long NOT NULL,
	[Objectives] Text(50) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdObjectives])
)
;

CREATE TABLE [T_Managtype_medConsGest]
(
	[IdObjectives] Long NULL,
	[IdManagementAndConservationType] Long NOT NULL,
	[codigo] Text(255) NULL,
	[Managementtype] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdManagementAndConservationType])
)
;

CREATE TABLE [T_MeasurementAccuracy]
(
	[IdMeasuremenAccuracy] Double NOT NULL,
	[MeasurementAccuracy] Text(255) NOT NULL,
	CONSTRAINT [PK_T_MeasurementAccuracy] PRIMARY KEY ([MeasurementAccuracy])
)
;

CREATE TABLE [T_Measurementmethod]
(
	[IdMeasuremenType] Double NULL,
	[idmethod] Long NOT NULL,
	[method] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idmethod]),
	CONSTRAINT [FK_T_Measurementmethod_T_MeasurementType] FOREIGN KEY ([IdMeasuremenType]) REFERENCES [T_MeasurementType] ([IdMeasuremenType])
)
;

CREATE TABLE [T_MeasurementType]
(
	[IdMeasuremenType] Double NOT NULL,
	[MeasuremenType] Text(255) NULL,
	CONSTRAINT [IdMeasuremenType] PRIMARY KEY ([IdMeasuremenType])
)
;

CREATE TABLE [T_measurementUnit]
(
	[IdMeasurementType] Long NULL,
	[IdMeasurementUnit] Long NOT NULL,
	[MeasurementUnit] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdMeasurementUnit]),
	CONSTRAINT [T_MeasurementTypeT_measurementUnit] FOREIGN KEY ([IdMeasurementType]) REFERENCES [T_MeasurementType] ([IdMeasuremenType])
)
;

CREATE TABLE [T_measurementValue]
(
	[IdMeasurementType] Double NULL,
	[idmethod] Long NULL,
	[id] Double NOT NULL,
	[Value] Text(255) NULL,
	CONSTRAINT [idHabitat] PRIMARY KEY ([id]),
	CONSTRAINT [FK_T_measurementValue_T_MeasurementType] FOREIGN KEY ([IdMeasurementType]) REFERENCES [T_MeasurementType] ([IdMeasuremenType]),
	CONSTRAINT [T_measurementValue_T_Measurementmethod] FOREIGN KEY ([idmethod]) REFERENCES [T_Measurementmethod] ([idmethod])
)
;

CREATE TABLE [T_NORMA_COMPONENTE]
(
	[ID_NORMA] Long NOT NULL,
	[ID_COMPONENTE] Long NOT NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([ID_NORMA],[ID_COMPONENTE]),
	CONSTRAINT [{DEA30950-C31D-47B8-80AF-C2895A691A3E}] FOREIGN KEY ([ID_NORMA]) REFERENCES [T_NORMA_TEMA] ([ID_NORMA]),
	CONSTRAINT [T_COMPONENTEST_NORMA_COMPONENTE] FOREIGN KEY ([ID_COMPONENTE]) REFERENCES [T_COMPONENTES] ([ID_COMPONENTE]),
	CONSTRAINT [T_NORMAST_NORMA_COMPONENTE] FOREIGN KEY ([ID_NORMA]) REFERENCES  ()
)
;

CREATE TABLE [T_NORMA_TEMA]
(
	[ID_NORMA] Long NOT NULL,
	[ID_TEMA] Long NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([ID_NORMA]),
	CONSTRAINT [{D0C2FF65-0746-4640-87B8-38B668B8D7E6}] FOREIGN KEY ([ID_TEMA]) REFERENCES [T_TEMAS] ([ID_TEMA])
)
;

CREATE TABLE [T_NORMAS]
(
	[ID_NORMA] Long NULL,
	[NORMA] Text(255) NULL,
	[URL] Text(255) NULL,
	[ANIO] Long NULL,
	[PARA_INFORME] Text(255) NULL,
	[FECHA] DateTime NULL,
	[ZZ_ORGANISMO] Text(255) NULL,
	[ID_ORGANISMO] Long NULL,
	[ID_USUARIO] Long NULL,
	[ZZ_RANGO_NORMA] Text(255) NULL,
	[ID_RANGO_NORMA_SUP] Long NULL,
	[ID_RANGO_NORMA_INT] Long NULL,
	[ID_RANGO_NORMA_INF] Long NULL,
	[ID_APLICACION] Long NULL,
	[ID_NORMA_CDDA] Text(255) NULL,
	[nombre_corto] Text(255) NULL,
	[norma_actualizada] Text(255) NULL,
	CONSTRAINT [T_RANGOS_NORMA_INFT_NORMAS] FOREIGN KEY ([ID_RANGO_NORMA_INF]) REFERENCES [T_RANGOS_NORMA_INF] ([ID_RANGO_NORMA]),
	CONSTRAINT [T_RANGOS_NORMA_INTT_NORMAS] FOREIGN KEY ([ID_RANGO_NORMA_INT]) REFERENCES [T_RANGOS_NORMA_INT] ([ID_RANGO_NORMA]),
	CONSTRAINT [T_RANGOS_NORMA_SUPT_NORMAS] FOREIGN KEY ([ID_RANGO_NORMA_SUP]) REFERENCES [T_RANGOS_NORMA_SUP] ([ID_RANGO_NORMA])
)
;

CREATE TABLE [T_NUTS]
(
	[CAutonomISO] Text(255) NULL,
	[CProvISO] Text(255) NULL,
	[NOMBRE _NUT2] Text(255) NULL,
	[NUT2] Double NULL,
	[NOMBRE_NUT3] Text(255) NULL,
	[NUT3] Double NULL,
	[CodINE] Double NULL,
	[Id] Counter NOT NULL,
	[NombINE_Prov] Text(255) NULL,
	[IdDistribution] Long NULL,
	CONSTRAINT [Id] PRIMARY KEY ([Id])
)
;

CREATE TABLE [T_organismos]
(
	[Id] Counter NOT NULL,
	[DESCRIPCION] Text(255) NULL,
	[ID_ORGANISMO] Double NULL,
	[NOMBRE] Text(255) NULL,
	CONSTRAINT [Id] PRIMARY KEY ([Id]),
	CONSTRAINT [T_NORMAST_organismos] FOREIGN KEY ([ID_ORGANISMO]) REFERENCES  ()
)
;

CREATE TABLE [T_poblacion_applies]
(
	[geoEntity] Text(255) NOT NULL,
	CONSTRAINT [PK_T_poblacion_applies] PRIMARY KEY ([geoEntity])
)
;

CREATE TABLE [T_PresAmen_cod]
(
	[Codigo0] Text(255) NULL,
	[Codigo1] Text(255) NULL,
	[Codigo] Text(255) NULL,
	[Codigo2] Text(255) NULL,
	[Id] Counter NOT NULL,
	[Value] Text(255) NULL,
	[Valor] Text(255) NULL,
	CONSTRAINT [Id] PRIMARY KEY ([Id])
)
;

CREATE TABLE [T_PresAmen_cod0]
(
	[Codigo0] Text(255) NULL,
	[Id] Counter NOT NULL,
	[Value] Text(255) NULL,
	[Valor] Text(255) NULL,
	CONSTRAINT [Id] PRIMARY KEY ([Id])
)
;

CREATE TABLE [T_PresAmen_cod1]
(
	[codigo0] Text(255) NULL,
	[codigo1] Text(255) NULL,
	[Id] Counter NOT NULL,
	[Value] Text(255) NULL,
	[Valor] Text(255) NULL,
	CONSTRAINT [Id] PRIMARY KEY ([Id])
)
;

CREATE TABLE [T_PresAmen_cod2]
(
	[Codigo0] Text(255) NULL,
	[Codigo1] Text(255) NULL,
	[Codigo2] Text(255) NULL,
	[Id] Counter NOT NULL,
	[Value] Text(255) NULL,
	[Valor] Text(255) NULL,
	CONSTRAINT [Id] PRIMARY KEY ([Id])
)
;

CREATE TABLE [T_PublicationType]
(
	[IdPublicationType] Long NOT NULL,
	[PublicationType] Text(50) NULL,
	[Publicacion] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdPublicationType])
)
;

CREATE TABLE [T_RANGOS_NORMA_INF]
(
	[ID_RANGO_NORMA] Long NOT NULL,
	[RANGO_NORMA] Text(255) NULL,
	[ID_RANGO_SUP] Long NULL,
	[ID_RANGO_INT] Long NULL,
	[DESCRIPCION] Memo NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([ID_RANGO_NORMA])
)
;

CREATE TABLE [T_RANGOS_NORMA_INT]
(
	[ID_RANGO_NORMA] Long NOT NULL,
	[RANGO_NORMA] Text(255) NULL,
	[ID_RANGO_SUP] Long NULL,
	[DESCRIPCION] Memo NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([ID_RANGO_NORMA])
)
;

CREATE TABLE [T_RANGOS_NORMA_SUP]
(
	[ID_RANGO_NORMA] Long NOT NULL,
	[RANGO_NORMA] Text(255) NULL,
	[DESCRIPCION] Memo NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([ID_RANGO_NORMA])
)
;

CREATE TABLE [T_RegBiog]
(
	[Id] Long NULL,
	[codigo] Text(255) NULL,
	[geoEntity] Text(255) NULL,
	CONSTRAINT [ManagementAndConservationT_RegBiog] FOREIGN KEY ([Id]) REFERENCES  ()
)
;

CREATE TABLE [T_RelatedResourceType]
(
	[IdRelatedResourceType] Long NOT NULL,
	[relatedResourceType] Text(255) NULL,
	[Campo1] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdRelatedResourceType])
)
;

CREATE TABLE [T_Status]
(
	[IdStatus] Long NOT NULL,
	[Status] Text(50) NULL,
	[Estado] Text(50) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdStatus])
)
;

CREATE TABLE [T_TaxonomicStatus]
(
	[IdTaxonomicStatus] Long NOT NULL,
	[TaxonomicStatus] Text(50) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdTaxonomicStatus])
)
;

CREATE TABLE [T_Taxonrank]
(
	[IdTaxonrank] Long NOT NULL,
	[Taxonrank] Text(50) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdTaxonrank])
)
;

CREATE TABLE [T_TEMAS]
(
	[ID_TEMA] Long NOT NULL,
	[TEMA] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([ID_TEMA])
)
;

CREATE TABLE [T_ThreatCategory]
(
	[IdThreatCategory] Long NOT NULL,
	[IdAuthority] Long NULL,
	[Category] Text(255) NULL,
	[Campo1] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdThreatCategory])
)
;

CREATE TABLE [T_ThreatStatus_appliesTo]
(
	[IdAppliesTo] Long NOT NULL,
	[Appliesto] Text(255) NULL,
	[IdAuthority] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdAppliesTo])
)
;

CREATE TABLE [T_Threatstatus_authority]
(
	[IdAuthority] Long NOT NULL,
	[Authority] Text(25) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdAuthority])
)
;

CREATE TABLE [T_Type]
(
	[IdType] Long NOT NULL,
	[Type] Text(50) NULL,
	[Description] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([IdType])
)
;

CREATE TABLE [Taxon]
(
	[TaxonID] Long NOT NULL,
	[taxonConceptID] Text(255) NULL,
	[scientificName] Text(255) NULL,
	[originalNameUsage] Text(255) NULL,
	[nameAccordingto] Memo NULL,
	[namePublishedIn] Memo NULL,
	[namePublishedInYear] Long NULL,
	[higherClassification] Text(255) NULL,
	[Idkingdom] Long NULL,
	[kingdom] Text(255) NULL,
	[idphylum] Long NULL,
	[phylum] Text(255) NULL,
	[idclass] Long NULL,
	[class] Text(255) NULL,
	[idorder] Long NULL,
	[order] Text(255) NULL,
	[idfamily] Long NULL,
	[family] Text(255) NULL,
	[idgenus] Long NULL,
	[genus] Text(255) NULL,
	[idsubgenus] Long NULL,
	[subgenus] Text(255) NULL,
	[idspecificepithet] Long NULL,
	[specificEpithet] Text(255) NULL,
	[idinfraspecificepithet] Long NULL,
	[infraspecificEpithet] Text(255) NULL,
	[idtaxonrank] Long NULL,
	[taxonRank] Text(255) NULL,
	[verbatimTaxonRank] Text(255) NULL,
	[ScientificNameAuthorship] Text(255) NULL,
	[IdNomenclaturalCode] Long NULL,
	[IdTaxonomicStatus] Long NULL,
	[NomenclaturalStatus] Text(50) NULL,
	[taxonRemarks] Memo NULL,
	[modified] DateTime NULL,
	[IdLanguage] Long NULL,
	[rights] Text(50) NULL,
	[rightsHolder] Text(50) NULL,
	[accessRights] Text(50) NULL,
	[bibliographicCitation] Text(50) NULL,
	[InformationWithHeld] Text(50) NULL,
	[IdRefrendado] Long NULL,
	[taxonRecordID] Long NULL,
	[Eunis_code] Text(255) NULL,
	[Euring_code] Text(255) NULL,
	[CITES_code] Text(255) NULL,
	[RedNatura_code] Text(255) NULL,
	[cod_ambito] Text(2) NULL,
	[idgrupotaxonomico] Long NULL,
	[GrupoTaxonomico] Text(255) NULL,
	[Id_img_fototeca] Long NULL,
	[SinAutor] Text(255) NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([TaxonID]),
	CONSTRAINT [BDN_RefrendadoTaxon] FOREIGN KEY ([IdRefrendado]) REFERENCES [BDN_Refrendado] ([IdRefrendado]),
	CONSTRAINT [EndemicTaxon] FOREIGN KEY ([taxonRecordID]) REFERENCES  (),
	CONSTRAINT [PlinianCore-ExtensionTaxon] FOREIGN KEY ([taxonRecordID]) REFERENCES [PlinianCore-Extension] ([TaxonRecordId]),
	CONSTRAINT [T_AMBITOSTaxon] FOREIGN KEY ([cod_ambito]) REFERENCES [T_AMBITOS] ([COD_AMBITO]),
	CONSTRAINT [T_grupoTaxonomicoTaxon1] FOREIGN KEY ([idgrupotaxonomico]) REFERENCES [T_grupoTaxonomico] ([Idgrupotax]),
	CONSTRAINT [T_TaxonrankTaxon] FOREIGN KEY ([idtaxonrank]) REFERENCES [T_Taxonrank] ([IdTaxonrank]),
	CONSTRAINT [Taxon-tiene-VernacularTaxon] FOREIGN KEY ([TaxonID]) REFERENCES  ()
)
;

CREATE TABLE [Taxon-EOL:Media]
(
	[TaxonID] Long NOT NULL,
	[IdMedia] Long NOT NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([TaxonID],[IdMedia]),
	CONSTRAINT [EOL:MediaTaxon-EOL:Media] FOREIGN KEY ([IdMedia]) REFERENCES  (),
	CONSTRAINT [TaxonTaxon-EOL:Media] FOREIGN KEY ([TaxonID]) REFERENCES  ()
)
;

CREATE TABLE [Taxon-tiene-Vernacular]
(
	[TaxonID] Long NOT NULL,
	[idVernacularName] Long NOT NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([TaxonID],[idVernacularName]),
	CONSTRAINT [VernacularNameTaxon-tiene-Vernacular] FOREIGN KEY ([idVernacularName]) REFERENCES [VernacularName] ([idVernacularName])
)
;

CREATE TABLE [ThreatStatus]
(
	[idThreatStatus] Long NOT NULL,
	[IdThreatCategory] Long NULL,
	[IdAuthority] Long NULL,
	[idAppliesTo] Long NULL,
	[TaxonRecordID] Long NULL,
	[Norm] Text(50) NULL,
	[Criterios] Memo NULL,
	[Year] Long NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idThreatStatus]),
	CONSTRAINT [PlinianCore-ExtensionThreatStatus] FOREIGN KEY ([TaxonRecordID]) REFERENCES [PlinianCore-Extension] ([TaxonRecordId]),
	CONSTRAINT [T_ThreatCategoryThreatStatus] FOREIGN KEY ([IdThreatCategory]) REFERENCES [T_ThreatCategory] ([IdThreatCategory]),
	CONSTRAINT [T_ThreatStatus_appliesToThreatStatus1] FOREIGN KEY ([idAppliesTo]) REFERENCES [T_ThreatStatus_appliesTo] ([IdAppliesTo]),
	CONSTRAINT [T_Threatstatus_authorityThreatStatus1] FOREIGN KEY ([IdAuthority]) REFERENCES [T_Threatstatus_authority] ([IdAuthority])
)
;

CREATE TABLE [Uses]
(
	[idUses] Long NOT NULL,
	[SourceOfInformation] Text(50) NULL,
	[Use-Value] Text(50) NULL,
	[PartUsed] Text(50) NULL,
	[Users] Text(50) NULL,
	[Organisms] Text(50) NULL,
	[VernacularNameUseAnnotations] Text(50) NULL,
	[ProductionDetails] Text(50) NULL,
	[MeansOfApplication-Administration] Text(50) NULL,
	[SeasonOfAvailability-Use] Text(50) NULL,
	[Conservation-ExplotationData] Text(50) NULL,
	[UseTypeAtomized] Text(50) NULL,
	[Economics] Text(50) NULL,
	[RatingPopularity] Text(50) NULL,
	[Properties] Text(50) NULL,
	[Potential] Text(50) NULL,
	[UseNotes] Text(50) NULL,
	[TaxonRecordID] Long NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idUses]),
	CONSTRAINT [PlinianCore-ExtensionUses] FOREIGN KEY ([TaxonRecordID]) REFERENCES [PlinianCore-Extension] ([TaxonRecordId])
)
;

CREATE TABLE [VernacularName]
(
	[idVernacularName] Long NOT NULL,
	[vernacularName] Text(255) NULL,
	[source] Text(255) NULL,
	[temporal] Text(255) NULL,
	[locationID] Text(255) NULL,
	[locality] Text(255) NULL,
	[IdSex] Long NULL,
	[IdLifeStage] Long NULL,
	[isPlural] YesNo NOT NULL,
	[isPreferredName] YesNo NOT NULL,
	[organismPart] Text(50) NULL,
	[taxonRemarks] Text(50) NULL,
	[IdLanguage] Long NULL,
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([idVernacularName]),
	CONSTRAINT [FK_VernacularName_T_Language] FOREIGN KEY ([IdLanguage]) REFERENCES [T_Language] ([IdLanguage])
)
;
